namespace: vdt-final
replicaCount: 1

image:
  repository: vuong676/listvdt-frontend-web
  tag: 5.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30911

env:
  REACT_APP_BACKEND_API_URL: "http://192.168.1.29:30852/api"
